config/routes.rb
Rails.application.routes.draw do
  resources :sales
  resources :purchases
  resources :products
  resources :product_categories
  resources :dailies
  resources :type_students
  resources :students
  resources :school_classes
  resources :teachers
  resources :periods
  devise_for :users

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'school_classes#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/daily.rb
class Daily < ApplicationRecord
  belongs_to :school_class

  has_many :school_attendances
  accepts_nested_attributes_for :school_attendances, allow_destroy: true
end

app/models/period.rb
class Period < ApplicationRecord
    has_many :school_classes
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :product_category
  has_many :purchases
  has_many :sales
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
    has_many :products
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :product
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :product
end

app/models/school_attendance.rb
class SchoolAttendance < ApplicationRecord
  belongs_to :student
  belongs_to :daily
end

app/models/school_class.rb
class SchoolClass < ApplicationRecord
  belongs_to :period
  belongs_to :teacher

  has_many :students
  accepts_nested_attributes_for :students, allow_destroy: true

  has_many :dailies
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :school_class
  belongs_to :type_student
  has_many :school_attendances
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    has_many :school_classes
end

app/models/type_student.rb
class TypeStudent < ApplicationRecord
    has_many :students
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  

  def assign_default_role
    self.add_role(:basic) if self.roles.blank?
  end
end

app/controllers/school_classes_controller.rb
class SchoolClassesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_school_class, only: [:show, :edit, :update, :destroy]

  # GET /school_classes
  def index
    @school_classes = SchoolClass.all
  end

   
  # GET /school_classes/1
  def show
  end


  

  # GET /school_classes/new
  def new
    @school_class = SchoolClass.new
  end

  # GET /school_classes/1/edit
  def edit
  end

  # POST /school_classes
  def create
    @school_class = SchoolClass.new(school_class_params)

    if @school_class.save
      redirect_to @school_class, notice: 'School class was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /school_classes/1
  def update
    if @school_class.update(school_class_params)
      redirect_to @school_class, notice: 'School class was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /school_classes/1
  def destroy
    @school_class.destroy
    redirect_to school_classes_url, notice: 'School class was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school_class
      @school_class = SchoolClass.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def school_class_params
      params.require(:school_class).permit(:description, :period_id, :teacher_id,  students_attributes: [
        :id, :_destroy, :name, :birth, :address, :phone, :email, :type_student_id])
    end
end

app/helpers/dailies_helper.rb
module DailiesHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/school_classes_helper.rb
module SchoolClassesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/school_classes/_form.html.erb
<%= simple_form_for(@school_class) do |f| %>
  <div class="box box-danger">
    <div class="box-header with-border">
      <h3 class="box-title">
        Dados do <%=t SchoolClass.model_name.human %>
      </h3>
    </div>
    <div class="box-body">
      <%= f.input :description %>
      <%= f.association :period, label_method: :description %>
      <%= f.association :teacher %>
    </div>

    <div class="nav-tabs-custom">
      <ul class="nav nav-tabs">
        <li class="active"><a href="#tab_1" data-toggle="tab"><%=t Student.model_name.human.pluralize %></a></li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="tab_1">
          <div id="students">
            <%= f.simple_fields_for :students do |part| %>
              <%= render 'student_fields', f: part %>
            <% end %>
            <div class="student_links">
              <%= link_to_add_association f, :students, class: 'btn btn-xs btn-primary' do %>
                <i class="fa fa-fw fa-plus"></i> Adicionar Aluno
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>    

    <div class="box-footer">
      <%= link_to t('.cancel', default: t("helpers.links.cancel")), school_classes_path, class: 'btn btn-default'  %>
      <%= f.submit  t('.save', default: t("helpers.links.save")), class: 'btn btn-danger' %>
    </div>
  </div>
<% end %>

app/views/school_classes/_student_fields.html.erb
<div class="box box-danger nested-fields">
  <div class="box-header with-border">
    <h3 class="box-title">
      <%=t Student.model_name.human %>
    </h3>
    <div class="box-tools pull-right">
      <%= link_to_remove_association f, class: 'btn btn-box-tool' do %>
        <i class="fa fa-fw fa-close"></i>
      <% end %>
    </div>
  </div>
  <div class="box-body">
    <div class="row">
      <%= f.input :name, wrapper_html: { class: 'col-md-8' } %>
      <%= f.input :birth, as: :date, start_year: Date.today.year - 90,
             end_year: Date.today.year - 12, order: [:day, :month, :year],
             html5: true, wrapper_html: { class: 'col-md-4' } %>

      <%= f.input :address, wrapper_html: { class: 'col-md-2' } %>
      <%= f.input :phone, wrapper_html: { class: 'col-md-2' } %>
      <%= f.input :email, wrapper_html: { class: 'col-md-3' } %>
      <%= f.association :type_student, wrapper_html: { class: 'col-md-3' } %>
    </div>

  </div>
</div>

app/views/school_classes/edit.html.erb
<%= render 'form' %>

app/views/school_classes/index.html.erb
<div class="box box-danger">
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th><%= SchoolClass.human_attribute_name(:description) %></th>
        <th><%= SchoolClass.human_attribute_name(:period) %></th>
        <th><%= SchoolClass.human_attribute_name(:teacher) %></th>
        <th class='text-center'><%=t '.actions', default: t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @school_classes.each do |school_class| %>
        <tr>
          <td>
            <%= link_to school_class.id, school_class, class: 'number bg-black' %>
          </td>
          <td>
            <%= school_class.description %>
          </td>
          <td>
            <%= school_class.period.description if school_class.period %>
          </td>
          <td>
            <%= school_class.teacher.name if school_class.teacher %>
          </td>
          <td style='white-space: nowrap' class='text-center'>
            <%= render 'shared/action_links', object: school_class %>
            <%= link_to new_daily_path(school_class_id: school_class.id), data: { toggle: 'tooltip', placement: 'top', title: 'Dailies'}, class: 'btn btn-xs btn-primary' do %>
              <i class="fa fa-calendar-plus-o"></i>
            <% end %>
            <%= link_to dailies_path(school_class_id: school_class.id), data: { toggle: 'tooltip', placement: 'top', title: 'Dailies'}, class: 'btn btn-xs btn-primary' do %>
              <i class="fa fa-calendar"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/school_classes/new.html.erb
<%= render 'form' %>

app/views/school_classes/show.html.erb
<div class="box box-danger">
  <div class="box-header with-border">
    <h3 class="box-title">
      <%=t SchoolClass.model_name.human %>
    </h3>
  </div>
  <div class="box-body">
    <div class="fieldset">
      <dl>
        <dt><%= SchoolClass.human_attribute_name(:description) %></dt>
        <dd><pre class="prettyprint"><%= @school_class.description %>&nbsp;</pre></dd>
        <dt><%= SchoolClass.human_attribute_name(:period) %></dt>
        <dd><pre class="prettyprint"><%= @school_class.period.description if @school_class.period %>&nbsp;</pre></dd>
        <dt><%= SchoolClass.human_attribute_name(:teacher) %></dt>
        <dd><pre class="prettyprint"><%= @school_class.teacher.name if @school_class.teacher %>&nbsp;</pre></dd>
      </dl>
    </div>
  </div>

      <div class="box-footer">
      <%= link_to t('.back', default: t("helpers.links.back")),
                  school_classes_path, class: 'btn btn-default'  %>
      <%= link_to t('.edit', default: t("helpers.links.edit")),
                  edit_school_class_path(@school_class), class: 'btn btn-default' %>
      <%= link_to t('.destroy', default: t("helpers.links.destroy")),
                  school_class_path(@school_class),
                  method: 'delete',
                  data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
                  class: 'btn btn-danger' %>
  </div>

  <div class="box box-danger">
    <div class="box-header with-border">
        <h3 class="box-title">
          <%=t Student.model_name.human.pluralize %>
        </h3>
    </div>              

  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th><%= Student.human_attribute_name(:name) %></th>
        <th><%= Student.human_attribute_name(:birth) %></th>
        <th><%= Student.human_attribute_name(:address) %></th>
        <th><%= Student.human_attribute_name(:email) %></th>
        <th><%= Student.human_attribute_name(:phone) %></th>
        <th><%= Student.human_attribute_name(:type_student) %></th>
        <th class='text-center'><%=t '.actions', default: t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @school_class.students.each do |student| %>
        <tr>
          <td>
            <%= link_to student.id, student, class: 'number bg-black' %>
          </td>
          <td>
            <%= student.name %>
          </td>
          <td>
            <%= student.birth %>
          </td>
          <td>
            <%= student.address %>
          </td>
          <td>
            <%= student.email %>
          </td>
          <td>
            <%= student.phone %>
          </td>

          <td>
            <%= student.type_student.name %>
          </td>

          <td style='white-space: nowrap' class='text-center'>
            <%= render 'shared/action_links', object: student %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>





</div>