config/routes.rb
Rails.application.routes.draw do
  resources :sales
  resources :purchases
  resources :products
  resources :product_categories
  resources :dailies
  resources :type_students
  resources :students
  resources :school_classes
  resources :teachers
  resources :periods
  devise_for :users

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'school_classes#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/daily.rb
class Daily < ApplicationRecord
  belongs_to :school_class

  has_many :school_attendances
  accepts_nested_attributes_for :school_attendances, allow_destroy: true
end

app/models/period.rb
class Period < ApplicationRecord
    has_many :school_classes
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :product_category
  has_many :purchases
  has_many :sales
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
    has_many :products
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :product
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :product
end

app/models/school_attendance.rb
class SchoolAttendance < ApplicationRecord
  belongs_to :student
  belongs_to :daily
end

app/models/school_class.rb
class SchoolClass < ApplicationRecord
  belongs_to :period
  belongs_to :teacher

  has_many :students
  accepts_nested_attributes_for :students, allow_destroy: true

  has_many :dailies
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :school_class
  belongs_to :type_student
  has_many :school_attendances
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    has_many :school_classes
end

app/models/type_student.rb
class TypeStudent < ApplicationRecord
    has_many :students
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  

  def assign_default_role
    self.add_role(:basic) if self.roles.blank?
  end
end

app/controllers/dailies_controller.rb
class DailiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_daily, only: [:show, :edit, :update, :destroy]

  # GET /dailies
  def index
     @dailies = Daily.where(school_class_id: params[:school_class_id])
  end

  # GET /dailies/1
  def show
  end

  # GET /dailies/new
  def new
    @daily = Daily.new
    @school_class = SchoolClass.find(params[:school_class_id])
    
    
    @daily.school_class = @school_class
    puts @daily.school_class
   

    @school_class.students.each do |student|
      @school_attendances = SchoolAttendance.new      
      @school_attendances.student = student
      @daily.school_attendances << @school_attendances
    end  
  end

  # GET /dailies/1/edit
  def edit
  end

  # POST /dailies
  def create
    
    @daily = Daily.new(daily_params)    

    if @daily.save!
      redirect_to @daily, notice: 'Daily was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /dailies/1
  def update
    if @daily.update(daily_params)
      redirect_to @daily, notice: 'Daily was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /dailies/1
  def destroy
    @daily.destroy
    redirect_to dailies_url, notice: 'Daily was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_daily
      @daily = Daily.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def daily_params
      params.require(:daily).permit(:date_daily, :school_class_id, school_attendances_attributes: [:presence, :_destroy, :student_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def eval_with_rescue(code)
    begin
      eval(code)
    rescue Exception => e
      "error"
    end
  end

  def bar_color(color="#ffffff")
    "<span class='btn btn-flat bg-black no-padding2' style='background: #{color} !important'>&nbsp;</span>".html_safe
  end
end

app/helpers/dailies_helper.rb
module DailiesHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/dailies/_form.html.erb
<%= simple_form_for(@daily) do |f| %>
  <div class="box box-danger">
    <div class="box-header with-border">
      <h3 class="box-title">
        Dados do <%=t Daily.model_name.human %> - <%=t SchoolClass.model_name.human %>:   <%= @daily.school_class.description %>
      </h3>
    </div>
    <div class="box-body">
      
      <%= f.input :date_daily, as: :date, start_year: Date.today,
                            end_year: Date.today,
                            order: [:day, :month, :year], html5: true, wrapper_html: { class: 'col-md-4' }%>

      <%= f.input :school_class_id, as: :hidden  %> 
    </div>
  </div>

  <div class="box box-danger">
      <div class="box-header with-border">
          <h3 class="box-title"> 
            <%=t SchoolAttendance.model_name.human.pluralize %>
          </h3>
      </div> 
      <div class="box-body">
          
        <table class="table">
            <thead>
              <tr>
                <th>#</th>
                <th><%= Student.model_name.human.pluralize %></th>
                <th>Presente</th>
                
              </tr>
            </thead>
          <tbody>
              <%= f.simple_fields_for :school_attendances do |p| %>  
                <tr>
                  <td>
                  <%= p.object.student_id  %>                  
                  </td>

                  <td>
                   <%= Student.find(p.object.student_id).name %> <%= p.input :student_id, as: :hidden  %>
                  </td>
                  <td>
                  <%= p.input :presence, wrapper_html: { class: 'col-md-3' } %>
                  </td>
                </tr>  
              <% end %>          
          </tbody>
        </table>    
    
      </div>
                        

    </div>      

    <div class="box-footer">
      <%= link_to t('.cancel', default: t("helpers.links.cancel")), dailies_path, class: 'btn btn-default'  %>
      <%= f.submit  t('.save', default: t("helpers.links.save")), class: 'btn btn-danger' %>
    </div>
  
<% end %>

app/views/dailies/_school_attendance_fields.html.erb
<div class="box box-danger nested-fields">
  <div class="box-header with-border">
    <h3 class="box-title">
      <%=t Student.model_name.human %>
    </h3>
    <div class="box-tools pull-right">
      <%= link_to_remove_association f, class: 'btn btn-box-tool' do %>
        <i class="fa fa-fw fa-close"></i>
      <% end %>
    </div>
  </div>
  <div class="box-body">
    <div class="row">
      <%= f.input :student, wrapper_html: { class: 'col-md-8' } %>
     

      <%= f.input :address, wrapper_html: { class: 'col-md-2' } %>
      <%= f.input :phone, wrapper_html: { class: 'col-md-2' } %>
      <%= f.input :email, wrapper_html: { class: 'col-md-3' } %>
      <%= f.association :type_student, wrapper_html: { class: 'col-md-3' } %>
    </div>

  </div>
</div>

app/views/dailies/edit.html.erb
<%= render 'form' %>

app/views/dailies/index.html.erb
<div class="box box-danger">
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th><%= Daily.human_attribute_name(:date_daily) %></th>
        <th><%= Daily.human_attribute_name(:school_class) %></th>
        <th class='text-center'><%=t '.actions', default: t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @dailies.each do |daily| %>
        <tr>
          <td>
            <%= link_to daily.id, daily, class: 'number bg-black' %>
          </td>
          <td>
            <%= daily.date_daily %>
          </td>
          <td>
            <%= daily.school_class.description if daily.school_class %>
          </td>
          <td style='white-space: nowrap' class='text-center'>
            <%= render 'shared/action_links', object: daily %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/dailies/new.html.erb
<%= render 'form' %>

app/views/dailies/show.html.erb
<div class="box box-danger">
  <div class="box-header with-border">
    <h3 class="box-title">
      <%=t Daily.model_name.human %>
    </h3>
  </div>
  <div class="box-body">
    <div class="fieldset">
      <dl>
        <dt><%= Daily.human_attribute_name(:date_daily) %></dt>
        <dd><pre class="prettyprint"><%= @daily.date_daily %>&nbsp;</pre></dd>
        <dt><%= Daily.human_attribute_name(:school_class) %></dt>
        <dd><pre class="prettyprint"><%= @daily.school_class.description if @daily.school_class %>&nbsp;</pre></dd>
      </dl>
    </div>
  </div>

  
  <div class="box-footer">
    <%= link_to t('.back', default: t("helpers.links.back")),
                dailies_path, class: 'btn btn-default'  %>
    <%= link_to t('.edit', default: t("helpers.links.edit")),
                edit_daily_path(@daily), class: 'btn btn-default' %>
    <%= link_to t('.destroy', default: t("helpers.links.destroy")),
                daily_path(@daily),
                method: 'delete',
                data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
                class: 'btn btn-danger' %>
  </div>




  <div class="box box-danger">
    <div class="box-header with-border">
        <h3 class="box-title">
          <%=t Student.model_name.human.pluralize %>
        </h3>
    </div>              

  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Aluno</th>
        <th>Tipo de Estudante</th>
        <th>Presente</th>   
        
      </tr>
    </thead>
    <tbody>
      <% @daily.school_attendances.each do |attendance| %>
        <tr>
          <td>
         
            <%=  link_to attendance.student.id,  student_path(attendance.student) %>
          </td>
          <td>
            <%= attendance.student.name %>
          </td>
          <td>
            <%= attendance.student.type_student.name %>
          </td>
          <td>
            <% if attendance.presence == true %>
              Presente
            <% else %>
              Faltou
            <% end %> 
          </td>
                    
        </tr>
      <% end %>
    </tbody>
  </table>





</div>