config/routes.rb
Rails.application.routes.draw do
  resources :sales
  resources :purchases
  resources :products
  resources :product_categories
  resources :dailies
  resources :type_students
  resources :students
  resources :school_classes
  resources :teachers
  resources :periods
  devise_for :users

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'school_classes#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/daily.rb
class Daily < ApplicationRecord
  belongs_to :school_class

  has_many :school_attendances
  accepts_nested_attributes_for :school_attendances, allow_destroy: true
end

app/models/period.rb
class Period < ApplicationRecord
    has_many :school_classes
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :product_category
  has_many :purchases
  has_many :sales
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
    has_many :products
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :product
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :product
end

app/models/school_attendance.rb
class SchoolAttendance < ApplicationRecord
  belongs_to :student
  belongs_to :daily
end

app/models/school_class.rb
class SchoolClass < ApplicationRecord
  belongs_to :period
  belongs_to :teacher

  has_many :students
  accepts_nested_attributes_for :students, allow_destroy: true

  has_many :dailies
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :school_class
  belongs_to :type_student
  has_many :school_attendances
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    has_many :school_classes
end

app/models/type_student.rb
class TypeStudent < ApplicationRecord
    has_many :students
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  

  def assign_default_role
    self.add_role(:basic) if self.roles.blank?
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  def create
    @sale = Sale.new(sale_params)
    @product = Product.find(@sale.product_id)
    
    @product.quantity_stock ||= 0
    @product.quantity_stock -= @sale.total_quantity
    
    if @sale.save
      @product.save
      redirect_to @sale, notice: 'Sale was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /sales/1
  def update
    if @sale.update(sale_params)
      redirect_to @sale, notice: 'Sale was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /sales/1
  def destroy
    @sale.destroy
    redirect_to sales_url, notice: 'Sale was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def sale_params
      params.require(:sale).permit(:date_sale, :unitary_value, :total_quantity, :amount, :cpf, :product_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def eval_with_rescue(code)
    begin
      eval(code)
    rescue Exception => e
      "error"
    end
  end

  def bar_color(color="#ffffff")
    "<span class='btn btn-flat bg-black no-padding2' style='background: #{color} !important'>&nbsp;</span>".html_safe
  end
end

app/helpers/dailies_helper.rb
module DailiesHelper
end

app/helpers/periods_helper.rb
module PeriodsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/sales/_form.html.erb
<%= simple_form_for(@sale) do |f| %>
  <div class="box box-danger">
    <div class="box-header with-border">
      <h3 class="box-title">
        Dados do <%=t Sale.model_name.human %>
      </h3>
    </div>
    <div class="box-body">
      <%= f.association :product, html5: true, wrapper_html: { class: 'col-md-6' }  %>
      <%= f.input :date_sale, as: :date,  start_year: Date.today.year - 10,
                              end_year: Date.today.year,
                              order: [:day, :month, :year], 
                              html5: true,  
                              wrapper_html: { class: 'col-md-2' }  %>
      <%= f.input :cpf, html5: true, wrapper_html: { class: 'col-md-4' }  %>
      <%= f.input :total_quantity, html5: true, wrapper_html: { class: 'col-md-4' } %>
      <%= f.input :unitary_value, html5: true, wrapper_html: { class: 'col-md-4' }  %>
     
      <%= f.input :amount, html5: true, wrapper_html: { class: 'col-md-4' }  %>
     
      
    </div>
    <div class="box-footer">
      <%= link_to t('.cancel', default: t("helpers.links.cancel")), sales_path, class: 'btn btn-default'  %>
      <%= f.submit  t('.save', default: t("helpers.links.save")), class: 'btn btn-danger' %>
    </div>
  </div>
<% end %>

app/views/sales/edit.html.erb
<%= render 'form' %>

app/views/sales/index.html.erb
<div class="box box-danger">
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th><%= Sale.human_attribute_name(:date_sale) %></th>
        <th><%= Sale.human_attribute_name(:unitary_value) %></th>
        <th><%= Sale.human_attribute_name(:total_quantity) %></th>
        <th><%= Sale.human_attribute_name(:amount) %></th>
        <th><%= Sale.human_attribute_name(:cpf) %></th>
        <th><%= Sale.human_attribute_name(:product) %></th>
        <th class='text-center'><%=t '.actions', default: t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% @sales.each do |sale| %>
        <tr>
          <td>
            <%= link_to sale.id, sale, class: 'number bg-black' %>
          </td>
          <td>
            <%= sale.date_sale %>
          </td>
          <td>
            <%= sale.unitary_value %>
          </td>
          <td>
            <%= sale.total_quantity %>
          </td>
          <td>
            <%= sale.amount %>
          </td>
          <td>
            <%= sale.cpf %>
          </td>
          <td>
            <%= sale.product.name if sale.product %>
          </td>
          <td style='white-space: nowrap' class='text-center'>
            <%= render 'shared/action_links', object: sale %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/sales/new.html.erb
<%= render 'form' %>

app/views/sales/show.html.erb
<div class="box box-danger">
  <div class="box-header with-border">
    <h3 class="box-title">
      <%=t Sale.model_name.human %>
    </h3>
  </div>
  <div class="box-body">
    <div class="fieldset">
      <dl>
        <dt><%= Sale.human_attribute_name(:product) %></dt>
        <dd><pre class="prettyprint"><%= @sale.product.name if @sale.product %>&nbsp;</pre></dd>
        <dt><%= Sale.human_attribute_name(:cpf) %></dt>
        <dd><pre class="prettyprint"><%= @sale.cpf %>&nbsp;</pre></dd>
        <dt><%= Sale.human_attribute_name(:date_sale) %></dt>
        <dd><pre class="prettyprint"><%= @sale.date_sale %>&nbsp;</pre></dd>
        <dt><%= Sale.human_attribute_name(:total_quantity) %></dt>
        <dd><pre class="prettyprint"><%= @sale.total_quantity %>&nbsp;</pre></dd>
        <dt><%= Sale.human_attribute_name(:unitary_value) %></dt>
        <dd><pre class="prettyprint"><%= @sale.unitary_value %>&nbsp;</pre></dd>        
        <dt><%= Sale.human_attribute_name(:amount) %></dt>
        <dd><pre class="prettyprint"><%= @sale.amount %>&nbsp;</pre></dd>
        
        
      </dl>
    </div>
  </div>
  <div class="box-footer">
    <%= link_to t('.back', default: t("helpers.links.back")),
                sales_path, class: 'btn btn-default'  %>
    <%= link_to t('.edit', default: t("helpers.links.edit")),
                edit_sale_path(@sale), class: 'btn btn-default' %>
    <%= link_to t('.destroy', default: t("helpers.links.destroy")),
                sale_path(@sale),
                method: 'delete',
                data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
                class: 'btn btn-danger' %>
  </div>
</div>